apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiptsnap-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: receiptsnap-backend
  template:
    metadata:
      labels:
        app: receiptsnap-backend
    spec:
      containers:
        - name: backend
          image: pratik50/receiptsnap-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "${DATABASE_URL}"
            - name: JWT_SECRET
              value: "${JWT_SECRET}"
            - name: AWS_ACCESS_KEY_ID
              value: "${AWS_ACCESS_KEY_ID}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "${AWS_SECRET_ACCESS_KEY}"
            - name: AWS_REGION
              value: "${AWS_REGION}"
            - name: AWS_BUCKET_NAME
              value: "${AWS_BUCKET_NAME}"
            - name: PORT
              value: "${PORT}"
              